# Generated by Django 5.1.5 on 2025-01-28 22:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Nickname can only contain letters, numbers, and underscores', regex='^[a-zA-Z0-9_]*$')])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=100)),
                ('energy', models.PositiveIntegerField(default=100)),
                ('max_energy', models.PositiveIntegerField(default=100)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('battles_fought', models.PositiveIntegerField(default=0)),
                ('creatures_caught', models.PositiveIntegerField(default=0)),
                ('items_collected', models.PositiveIntegerField(default=0)),
                ('quests_completed', models.PositiveIntegerField(default=0)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_energy_update', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['level', 'xp'], name='profile_level_xp_idx'), models.Index(fields=['wins', 'losses'], name='profile_wins_losses_idx')],
            },
        ),
    ]
