# Generated by Django 4.2.13 on 2024-07-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_player_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clan",
            name="emblem",
            field=models.ImageField(
                blank=True,
                default="default_emblem.jpg",
                null=True,
                upload_to="emblems/",
            ),
        ),
    ]
